# Generated by Django 2.2.3 on 2019-07-10 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0007_auto_20190710_1451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='tags',
        ),
    ]
